name: Deploy and Release
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

jobs:
  deploy-package:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
      PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
      PACKAGIST_API_TOKEN: ${{ secrets.PACKAGIST_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Setup Node
        run: |
          sudo apt update && sudo apt install nodejs

      - name: Install composer dependencies
        run: |
          composer --no-interaction --no-progress --prefer-dist install

      - name: Create Changelog
        id: changelog
        run: |
          npm install -g auto-changelog
          auto-changelog

      - name: Autocommit changelog
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: "CHANGELOG.md"
          draft: false
          prerelease: false
